### ISSUE TITLE
Statistic chooser does not register that the user already set the different parameters

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#101]
When the user switches back to the statistic chooser from the statistic he created, all parameters (except the dates) are preset to the values he put in earlier. The problem is that the system behind the ui does not register that and tells the user he did not select anything if he tries to recreate his statistic with that settings. You can even reselect all of the already selected parameters which causes a lot of confusion.

**Comment by aleksn41** [comment]
Not recreatable in the current master branch. This used to be an issue but was fixed in Pullrequest #95. You probably got this error in a Branch not up-to-date with master
