### ISSUE TITLE
Rework BottomSheetTitle

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#123]
BottomSheetTitle is to big for certain country names (Central African Republic, Democratic Republic of the Congo, ...). I see multiple options for resolving this: 
1.) Resize Font automatically 
2.) Make font size smaller (static)
3.) Try Wordwrapping the lines

**Comment by Tommy-FF** [comment]
This bug is especially annoying with the beta feature of the germany map. (Germany's states have long names)

**Comment by aleksn41** [comment]
Its better for the user experience to have a consistent text size. I will look into what font size fits the best. For the Germany Map, since it should be a seperate Fragment (see my comment in #122) it can be set seperately which should not be a problem.

**Comment by Tommy-FF** [comment]
Keep in mind that different users could have smartphones with bigger and smaller width (and height)

**Comment by aleksn41** [comment]
Yes but that will be handled in issue #44
