### ISSUE TITLE
User can select world in statistics chooser

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#141]
Since World is an ISOCountry the user can choose it through the statistics chooser. The problem is that our api used for the past data (which the user can select) does not support World as input. I see two ways to fix this:

1) Delete World from ISOCountry and make own class/enum just for World

2) Implement a rule so that the user can only select now as date when world is chosen 

What way do you think is best?

**Comment by aleksn41** [comment]
Changing the rule System for this case would be too time consuming right now. Please use the first approach

**Comment by aleksn41** [comment]
Since this is too much work, the item will just be blacklisted from statisic chooser, meaning it can never be chosen
