### ISSUE TITLE
User is not informed about any Errors

### ISSUE THREAD

**Issue by aleksn41** [aleksn41/corona_world_app#47]
UI needs to implement a window which every class can access, which is able to inform the User about an Error.

**Comment by aleksn41** [comment]
UI Errors are now shown to the User once the next UI Pull request is accepted

**Comment by aleksn41** [comment]
Map and Statistic need to Inform User if something goes wong

**Comment by aleksn41** [comment]
Create a Pull request for Map and Statistic and link it here before accepting Pull request #56

**Comment by aleksn41** [comment]
Error Messages are now handled with Error-Codes with a standardized message. If Time is left, a report action may be added.

**Comment by Tommy-FF** [comment]
was falsely linked

**Comment by Tommy-FF** [comment]
I would argue that this is not a feature a "Prototype" needs because it concerns only visuality not functionality

**Comment by Tommy-FF** [comment]
In the statistic branch all errors are displayed correctly

**Comment by Tommy-FF** [comment]
Oops, falsely closed issue

**Comment by Tommy-FF** [comment]
MapViewModel must delete Cache in case of error. The user is already informed properly.
