### ISSUE TITLE
Map of Germany

### ISSUE THREAD

**Issue by aleksn41** [aleksn41/corona_world_app#54]
It would be nice to have an explicit Map of Germany as a Beta feature. it is possible to generate the germany map with geochart see https://stamm-wilbrandt.de/en/gist/Germany.html. One could use the Data of the Robert-Koch-Institut to populate this map.
Please add this if you have enough time.

**Comment by Tommy-FF** [comment]
Setting it low prio, as it is not necessary and relatively time-consuming. As you said, will be done if I have no more important tasks...
