### ISSUE TITLE
Fill readme.md with basic desriptiption of the project

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#55]
For creating an overview the readme file should be filled. See https://github.com/jehna/readme-best-practices for info about how to create a good project readme file.

**Comment by aleksn41** [comment]
added a better README in #121

**Comment by Tommy-FF** [comment]
I added usage descriptions for both maps, statistic and the info & settings tab (this one's work in progress because the second setting (storage) won't be in the final version). See #161

**Comment by Tommy-FF** [comment]
Readme complete. See #165
