### ISSUE TITLE
Format total numbers in tooltips

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#77]
Total numbers in the tooltips are hard to read. E.g. 10000000 could be formatted as 10m or 100000 as 100k.

**Comment by Prom3thean** [comment]
As the library is very tricky in this regard, this will be implemented as a static box that can be opened and closed (top/bottom of the map screen) -> JavaScriptInterface will transition the country name from map to app.

**Comment by Tommy-FF** [comment]
Wait, I read wrong. This issue is already resolved
