### ISSUE TITLE
Notification if a country reaches a certain number in a certain criteria

### ISSUE THREAD

**Issue by aleksn41** [aleksn41/corona_world_app#78]
It would be nice if the user could set some parameter on which the user is informed of the state of a country via notifications

**Comment by Tommy-FF** [comment]
It certainly would be nice, but as it is low prio we will see if we have time to implement this...

**Comment by Tommy-FF** [comment]
As of now, I don't think we will have enough time to implement this. But we will see...

**Comment by Tommy-FF** [comment]
Will not be done due to shortage of time.
