### ISSUE TITLE
Create Text View instead of tooltips

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#99]
Instead of the built in tooltips we will now use a text box with the selected country's data.

**Comment by Tommy-FF** [comment]
Related to issue #43

**Comment by Tommy-FF** [comment]
Text View was created by @aleksn41 data now is shown in it. Awaiting redesign

**Comment by aleksn41** [comment]
Created a simple layout that shows the selected country with its respective data
